const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export {
  FORMULARIO_PROYECTO,
  OBTENER_PROYECTOS,
  AGREGAR_PROYECTO,
  VALIDAR_FORMULARIO,
  PROYECTO_ACTUAL,
  ELIMINAR_PROYECTO,
};
