const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
const AGREGAR_TAREAS = 'AGREGAR_TAREAS';
const VALIDAR_TAREA = 'VALIDAR_TAREA';
const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
const ESTADO_TAREA = 'ESTADO_TAREA';
const TAREA_ACTUAL = 'TAREA_ACTUAL';
const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export {
  FORMULARIO_PROYECTO,
  OBTENER_PROYECTOS,
  AGREGAR_PROYECTO,
  VALIDAR_FORMULARIO,
  PROYECTO_ACTUAL,
  ELIMINAR_PROYECTO,
  TAREAS_PROYECTO,
  AGREGAR_TAREAS,
  VALIDAR_TAREA,
  ELIMINAR_TAREA,
  ESTADO_TAREA,
  TAREA_ACTUAL,
  ACTUALIZAR_TAREA,
};
